export type Product = {
    id: number
    image:string
    category: string
    type: string
    itemName: string
    color: string
    size: string
    composition: string
    term: number
    price: number
}

const productsArray: Product[] = [
    {
        id: 1,
        image: '/images/grey_rabbit.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"СІРИЙ ВУХАНЬ"`,
        color: 'сірий',
        size: '30',
        composition: 'поліестер 100%',
        term: 550022,
        price: 989,
    },
    {
        id: 2,
        image: '/images/rabbit_in_glasses.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"ЗАЙЧИК В ОКУЛЯРАХ"`,
        color: 'персиковий',
        size: '30',
        composition: 'поліестер 100%',
        term: 550026,
        price: 989,
    },
    {
        id: 3,
        image: '/images/brown_bear.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"ВЕДМЕДИК"`,
        color: 'коричневий',
        size: '28',
        composition: 'поліестер 100%',
        term: 550025,
        price: 794,
    },
    {
        id: 4,
        image: '/images/giraffe.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"ЖИРАФ"`,
        color: 'жовтий',
        size: '28',
        composition: 'поліестер 100%',
        term: 550023,
        price: 859,
    },
    {
        id: 5,
        image: '/images/white_unicorn.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"ЄДИНОРІЖКА"`,
        color: 'білий',
        size: '28',
        composition: 'поліестер 100%',
        term: 550024,
        price: 729,
    },
    {
        id: 6,
        image: '/images/knitted_blanket_kudelka.jpg',
        category: 'textile',
        type: `Плед в'язаний`,
        itemName: `"КУДЕЛЬКА"`,
        color: 'блакитний, персиковий',
        size: '100*80',
        composition: 'поліестер 100%',
        term: 440015,
        price: 990,
    },
    {
        id: 7,
        image: '/images/sides_on_the_cradle.jpg',
        category: 'textile',
        type: `Бортики на колиску`,
        itemName: `"SAND" 120*60`,
        color: 'мокрий пісок',
        size: '6 шт.: 55*30',
        composition: 'бавовна, синтепон',
        term: 440020,
        price: 1139,
    },
    {
        id: 8,
        image: '/images/bedclothes_roslinka.jpg',
        category: 'textile',
        type: `Постільна білизна`,
        itemName: `"РОСЛИНКА"`,
        color: 'орнамент',
        size: 'підковдра 120*120; наволочка 40*60; простирадло на резинці 120*60',
        composition: 'бавовна 100%',
        term: 660030,
        price: 659,
    },
    {
        id: 9,
        image: '/images/orthopedic_pillow_roslinka.jpg',
        category: 'textile',
        type: `Подушка ортопедична`,
        itemName: `"РОСЛИНКА"`,
        color: 'принт',
        size: '30*25',
        composition: 'бавовна, холлофайбер',
        term: 330008,
        price: 254,
    },
    {
        id: 10,
        image: '/images/orthopedic_pillow_hmarinka.jpg',
        category: 'textile',
        type: `Подушка ортопедична`,
        itemName: `"ХМАРИНКА"`,
        color: 'білий, фіолетовий',
        size: '30*25',
        composition: 'бавовна, холлофайбер',
        term: 330008,
        price: 254,
    },
    {
        id: 11,
        image: '/images/pillow_for_pregnant_blue.jpg',
        category: 'pregnant',
        type: `Подушка для вагітних`,
        itemName: `"HAPPY MOTHER"`,
        color: 'блакитний',
        size: '150*70',
        composition: 'бавовна, холлофайбер',
        term: 330009,
        price: 939,
    },
    {
        id: 12,
        image: '/images/pillow_for_pregnant_turquoise.jpg',
        category: 'pregnant',
        type: `Подушка для вагітних`,
        itemName: `"HAPPY MOTHER"`,
        color: 'блакитний',
        size: '150*70',
        composition: 'бавовна, холлофайбер',
        term: 330009,
        price: 939,
    },
    {
        id: 13,
        image: '/images/pillow_for_feeding_grey_print.jpg',
        category: 'pregnant',
        type: `Подушка для годування`,
        itemName: `"SOFT CLOUD"`,
        color: 'принт, сірий',
        size: '53*40',
        composition: 'бавовна, холлофайбер',
        term: 330010,
        price: 520,
    },
    {
        id: 14,
        image: '/images/pillow_for_feeding_blue_print.jpg',
        category: 'pregnant',
        type: `Подушка для годування`,
        itemName: `"SOFT CLOUD"`,
        color: 'принт, блакитний',
        size: '53*40',
        composition: 'бавовна, холлофайбер',
        term: 330010,
        price: 520,
    },
]

export const getProductObject = (array: Product[]) => array.reduce((object, product) => ({
    ...object,
    [product.id]:product,
}),{})

export default productsArray