export type Product = {
    id: number
    description: string
    image:string
    category: string
    type: string
    itemName: string
    color: string
    size: string
    composition: string
    term: number
    price: number
}

const productsArray: Product[] = [
    {
        id: 1,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/grey_rabbit.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"СІРИЙ ВУХАНЬ"`,
        color: 'сірий',
        size: '30',
        composition: 'поліестер 100%',
        term: 550022,
        price: 989,
    },
    {
        id: 2,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/rabbit_in_glasses.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"ЗАЙЧИК В ОКУЛЯРАХ"`,
        color: 'персиковий',
        size: '30',
        composition: 'поліестер 100%',
        term: 550026,
        price: 989,
    },
    {
        id: 3,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/brown_bear.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"ВЕДМЕДИК"`,
        color: 'коричневий',
        size: '28',
        composition: 'поліестер 100%',
        term: 550025,
        price: 794,
    },
    {
        id: 4,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/giraffe.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"ЖИРАФ"`,
        color: 'жовтий',
        size: '28',
        composition: 'поліестер 100%',
        term: 550023,
        price: 859,
    },
    {
        id: 5,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/white_unicorn.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"ЄДИНОРІЖКА"`,
        color: 'білий',
        size: '28',
        composition: 'поліестер 100%',
        term: 550024,
        price: 729,
    },
    {
        id: 6,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/knitted_blanket_kudelka.jpg',
        category: 'textile',
        type: `Плед в'язаний`,
        itemName: `"КУДЕЛЬКА"`,
        color: 'блакитний, персиковий',
        size: '100*80',
        composition: 'поліестер 100%',
        term: 440015,
        price: 990,
    },
    {
        id: 7,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/sides_on_the_cradle.jpg',
        category: 'textile',
        type: `Бортики на колиску`,
        itemName: `"SAND" 120*60`,
        color: 'мокрий пісок',
        size: '6 шт.: 55*30',
        composition: 'бавовна, синтепон',
        term: 440020,
        price: 1139,
    },
    {
        id: 8,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/bedclothes_roslinka.jpg',
        category: 'textile',
        type: `Постільна білизна`,
        itemName: `"РОСЛИНКА"`,
        color: 'орнамент',
        size: 'підковдра 120*120; наволочка 40*60; простирадло на резинці 120*60',
        composition: 'бавовна 100%',
        term: 660030,
        price: 659,
    },
    {
        id: 9,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/orthopedic_pillow_roslinka.jpg',
        category: 'textile',
        type: `Подушка ортопедична`,
        itemName: `"РОСЛИНКА"`,
        color: 'принт',
        size: '30*25',
        composition: 'бавовна, холлофайбер',
        term: 330008,
        price: 254,
    },
    {
        id: 10,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/orthopedic_pillow_hmarinka.jpg',
        category: 'textile',
        type: `Подушка ортопедична`,
        itemName: `"ХМАРИНКА"`,
        color: 'білий, фіолетовий',
        size: '30*25',
        composition: 'бавовна, холлофайбер',
        term: 330008,
        price: 254,
    },
    {
        id: 11,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/pillow_for_pregnant_blue.jpg',
        category: 'pregnant',
        type: `Подушка для вагітних`,
        itemName: `"HAPPY MOTHER"`,
        color: 'блакитний',
        size: '150*70',
        composition: 'бавовна, холлофайбер',
        term: 330009,
        price: 939,
    },
    {
        id: 12,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/pillow_for_pregnant_turquoise.jpg',
        category: 'pregnant',
        type: `Подушка для вагітних`,
        itemName: `"HAPPY MOTHER"`,
        color: 'блакитний',
        size: '150*70',
        composition: 'бавовна, холлофайбер',
        term: 330009,
        price: 939,
    },
    {
        id: 13,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/pillow_for_feeding_grey_print.jpg',
        category: 'pregnant',
        type: `Подушка для годування`,
        itemName: `"SOFT CLOUD"`,
        color: 'принт, сірий',
        size: '53*40',
        composition: 'бавовна, холлофайбер',
        term: 330010,
        price: 520,
    },
    {
        id: 14,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/pillow_for_feeding_blue_print.jpg',
        category: 'pregnant',
        type: `Подушка для годування`,
        itemName: `"SOFT CLOUD"`,
        color: 'принт, блакитний',
        size: '53*40',
        composition: 'бавовна, холлофайбер',
        term: 330010,
        price: 520,
    },
    {
        id: 15,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/diaper_1.jpg',
        category: 'diapers',
        type: `Пелюшка`,
        itemName: ``,
        color: 'принт',
        size: '80*80',
        composition: 'бавовна, ситець',
        term: 220006,
        price: 125,
    },
    {
        id: 16,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/diaper_2.jpg',
        category: 'diapers',
        type: `Пелюшка утеплена`,
        itemName: ``,
        color: 'принт',
        size: '80*80',
        composition: '100% бавовна',
        term: 220005,
        price: 125,
    },
    {
        id: 17,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/diaper_3.jpg',
        category: 'diapers',
        type: `Пелюшка`,
        itemName: ``,
        color: 'принт',
        size: '80*80',
        composition: 'бавовна, ситець',
        term: 220006,
        price: 125,
    },
    {
        id: 18,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/diaper_4.jpg',
        category: 'diapers',
        type: `Пелюшка утеплена`,
        itemName: ``,
        color: 'принт',
        size: '80*80',
        composition: '100% бавовна',
        term: 220005,
        price: 125,
    },
    {
        id: 19,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/diaper_5.jpg',
        category: 'diapers',
        type: `Пелюшка утеплена`,
        itemName: ``,
        color: 'принт',
        size: '80*80',
        composition: '100% бавовна',
        term: 220005,
        price: 125,
    },
    {
        id: 20,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/bib_1.jpg',
        category: 'bibs',
        type: `Нагрудник непромокаючий`,
        itemName: `"КОНИКИ"`,
        color: 'принт',
        size: '',
        composition: 'бавовна, водонепроникна мембрана',
        term: 110002,
        price: 250,
    },
    {
        id: 21,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/plaid_cloud.jpg',
        category: 'textile',
        type: `Плед`,
        itemName: `"ХМАРИНКА"`,
        color: 'молоко',
        size: '80*80',
        composition: '100% поліестер',
        term: 440022,
        price: 990,
    },
    {
        id: 22,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/mattress_for_the_changing_table.jpg',
        category: 'textile',
        type: `Матрац для пеленального столика`,
        itemName: ``,
        color: 'блакитний, принт',
        size: '60*70',
        composition: 'бавовна, синтепон',
        term: 440023,
        price: 480,
    },
    {
        id: 23,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/towel_bear.jpg',
        category: 'towels',
        type: `Рушник`,
        itemName: `"ВЕДМЕЖАТКО"`,
        color: 'сірий',
        size: '80*80',
        composition: 'махра (100% бавовна)',
        term: 440017,
        price: 750,
    },
    {
        id: 24,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/cocoon_1.jpg',
        category: 'cocoons',
        type: `Кокон двосторонній`,
        itemName: `"ОБІЙМИ ЗВІРЯТ"`,
        color: 'пісок, принт',
        size: 'універсальний, регулюється',
        composition: 'бавовна, холлофайбер',
        term: 660029,
        price: 880,
    },
    {
        id: 25,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/cocoon_2.jpg',
        category: 'cocoons',
        type: `Кокон двосторонній`,
        itemName: `"PURPLE"`,
        color: 'бузковий',
        size: 'універсальний, регулюється',
        composition: 'бавовна, холлофайбер',
        term: 660028,
        price: 880,
    },
    {
        id: 26,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/cocoon_3.jpg',
        category: 'cocoons',
        type: `Кокон двосторонній`,
        itemName: `"КОНИКИ"`,
        color: `м'ята, принт`,
        size: 'універсальний, регулюється',
        composition: 'бавовна, холлофайбер',
        term: 660030,
        price: 880,
    },
    {
        id: 27,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/body_little_patriot.jpg',
        category: 'body',
        type: `Боді`,
        itemName: `"МАЛЕНЬКИЙ ПАТРІОТ"`,
        color: `білий`,
        size: '62, 68, 74, 80',
        composition: '100% бавовна',
        term: 770001,
        price: 199,
    },
    {
        id: 28,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/body_made_in_ukraine.jpg',
        category: 'body',
        type: `Боді`,
        itemName: `"MADE IN UKRAINE"`,
        color: `білий`,
        size: '62, 68, 74, 80',
        composition: '100% бавовна',
        term: 770002,
        price: 199,
    },
    {
        id: 29,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/body_somik.jpg',
        category: 'body',
        type: `Боді`,
        itemName: `"SOMIK"`,
        color: `білий`,
        size: '62, 68, 74, 80',
        composition: '100% бавовна',
        term: 770003,
        price: 199,
    },
    {
        id: 30,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/body_emblem.jpg',
        category: 'body',
        type: `Боді`,
        itemName: `"ГЕРБ"`,
        color: `білий`,
        size: '62, 68, 74, 80',
        composition: '100% бавовна',
        term: 770004,
        price: 199,
    },
    {
        id: 31,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/rattle_duckling.jpg',
        category: 'toys',
        type: `Брязкальце`,
        itemName: `"СЛОНЕНЯТКО"`,
        color: `білий`,
        size: '14',
        composition: 'мікрополіестер, береза',
        term: 550028,
        price: 220,
    },
    {
        id: 32,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/rattle_bunny_white.jpg',
        category: 'toys',
        type: `Брязкальце`,
        itemName: `"ЗАЙЧИК"`,
        color: `молоко`,
        size: '17',
        composition: 'мікрополіестер, береза',
        term: 550030,
        price: 220,
    },
    {
        id: 33,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/koala_rattle.jpg',
        category: 'toys',
        type: `Брязкальце`,
        itemName: `"КОАЛА"`,
        color: `сірий`,
        size: '14',
        composition: 'мікрополіестер, бук',
        term: 550029,
        price: 220,
    },
    {
        id: 34,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/rattle_bunny_grey.jpg',
        category: 'toys',
        type: `Брязкальце`,
        itemName: `"ЗАЙЧИК"`,
        color: `світло-сірий`,
        size: '17',
        composition: 'мікрополіестер, бук',
        term: 550031,
        price: 220,
    },
    {
        id: 35,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/slingbuses_beads.jpg',
        category: 'toys',
        type: `Слінгобуси`,
        itemName: `"BEADS"`,
        color: `беж, білий`,
        size: '25 см + резинка 10',
        composition: 'бавовна, дерево',
        term: 550031,
        price: 199,
    },
    {
        id: 36,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/pajama_elephant.jpg',
        category: 'toys',
        type: `Піжамниця в'язана`,
        itemName: `"СЛОНЕНЯ"`,
        color: `сірий`,
        size: '54',
        composition: 'мікрополіестер',
        term: 550033,
        price: 660,
    },
    {
        id: 37,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/mini_toy_dreamer.jpg',
        category: 'toys',
        type: `Міні-іграшка`,
        itemName: `"МРІЙЛИВКА"`,
        color: `білий, рожевий`,
        size: '12',
        composition: '55% бавовна, 45% поліакрил',
        term: 550032,
        price: 195,
    },
    {
        id: 38,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/toy_happy_bear.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"HAPPY BEAR"`,
        color: `молоко`,
        size: '25',
        composition: '55% бавовна, 45% поліакрил',
        term: 550034,
        price: 469,
    },
    {
        id: 39,
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum voluptatibus similique quasi eos mollitia nihil amet qui cum neque sapiente nobis laudantium optio ipsum architecto possimus laboriosam, veniam facilis. Quo eveniet pariatur aut nostrum hic distinctio esse architecto tempore voluptas totam. Repudiandae, optio, magni quidem temporibus vel excepturi vero obcaecati, quis corrupti at fugit dolores? Repudiandae quia a molestias dolores doloremque velit dolore ducimus, voluptatem, sunt, esse similique perferendis iste harum facilis maiores quis blanditiis? Sapiente, voluptas!',
        image: '/images/toy_cutie.jpg',
        category: 'toys',
        type: `Іграшка в'язана`,
        itemName: `"CUTIE"`,
        color: `молоко, рожевий`,
        size: '40',
        composition: '55% бавовна, 45% поліакрил',
        term: 550035,
        price: 469,
    },
]

export const getProductObject = (array: Product[]) => array.reduce((object, product) => ({
    ...object,
    [product.id]:product,
}),{})

export default productsArray